/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecruiterRouteImport } from './routes/_recruiter'
import { Route as InterviewTokenRouteImport } from './routes/interview/$token'
import { Route as RecruiterJobsIndexRouteImport } from './routes/_recruiter/jobs/index'
import { Route as RecruiterJobsJobIdRouteImport } from './routes/_recruiter/jobs/$jobId'
import { Route as RecruiterJobsNewRouteImport } from './routes/_recruiter/jobs/new'
import { Route as InterviewTokenIndexRouteImport } from './routes/interview/$token/index'
import { Route as InterviewTokenCompleteRouteImport } from './routes/interview/$token/complete'
import { Route as InterviewTokenDeviceCheckRouteImport } from './routes/interview/$token/device-check'
import { Route as InterviewTokenSessionRouteImport } from './routes/interview/$token/session'
import { Route as RecruiterJobsJobIdIndexRouteImport } from './routes/_recruiter/jobs/$jobId/index'
import { Route as RecruiterJobsJobIdDetailsRouteImport } from './routes/_recruiter/jobs/$jobId/details'
import { Route as RecruiterJobsJobIdInterviewRouteImport } from './routes/_recruiter/jobs/$jobId/interview'
import { Route as RecruiterJobsJobIdReportsRouteImport } from './routes/_recruiter/jobs/$jobId/reports'
import { Route as RecruiterJobsJobIdCandidatesIndexRouteImport } from './routes/_recruiter/jobs/$jobId/candidates/index'
import { Route as RecruiterJobsJobIdCandidatesCandidateIdRouteImport } from './routes/_recruiter/jobs/$jobId/candidates/$candidateId'
import { Route as RecruiterJobsJobIdCandidatesNewRouteImport } from './routes/_recruiter/jobs/$jobId/candidates/new'

const RecruiterRoute = RecruiterRouteImport.update({
  id: '/_recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewTokenRoute = InterviewTokenRouteImport.update({
  id: '/interview/$token',
  path: '/interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsIndexRoute = RecruiterJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterJobsJobIdRoute = RecruiterJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterJobsNewRoute = RecruiterJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => RecruiterRoute,
} as any)
const InterviewTokenIndexRoute = InterviewTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterviewTokenRoute,
} as any)
const InterviewTokenCompleteRoute = InterviewTokenCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => InterviewTokenRoute,
} as any)
const InterviewTokenDeviceCheckRoute =
  InterviewTokenDeviceCheckRouteImport.update({
    id: '/device-check',
    path: '/device-check',
    getParentRoute: () => InterviewTokenRoute,
  } as any)
const InterviewTokenSessionRoute = InterviewTokenSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => InterviewTokenRoute,
} as any)
const RecruiterJobsJobIdIndexRoute = RecruiterJobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterJobsJobIdRoute,
} as any)
const RecruiterJobsJobIdDetailsRoute =
  RecruiterJobsJobIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => RecruiterJobsJobIdRoute,
  } as any)
const RecruiterJobsJobIdInterviewRoute =
  RecruiterJobsJobIdInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => RecruiterJobsJobIdRoute,
  } as any)
const RecruiterJobsJobIdReportsRoute =
  RecruiterJobsJobIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => RecruiterJobsJobIdRoute,
  } as any)
const RecruiterJobsJobIdCandidatesIndexRoute =
  RecruiterJobsJobIdCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => RecruiterJobsJobIdRoute,
  } as any)
const RecruiterJobsJobIdCandidatesCandidateIdRoute =
  RecruiterJobsJobIdCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => RecruiterJobsJobIdRoute,
  } as any)
const RecruiterJobsJobIdCandidatesNewRoute =
  RecruiterJobsJobIdCandidatesNewRouteImport.update({
    id: '/candidates/new',
    path: '/candidates/new',
    getParentRoute: () => RecruiterJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RecruiterRouteWithChildren
  '/interview/$token': typeof InterviewTokenRouteWithChildren
  '/jobs/$jobId': typeof RecruiterJobsJobIdRouteWithChildren
  '/jobs/new': typeof RecruiterJobsNewRoute
  '/interview/$token/complete': typeof InterviewTokenCompleteRoute
  '/interview/$token/device-check': typeof InterviewTokenDeviceCheckRoute
  '/interview/$token/session': typeof InterviewTokenSessionRoute
  '/jobs/': typeof RecruiterJobsIndexRoute
  '/interview/$token/': typeof InterviewTokenIndexRoute
  '/jobs/$jobId/details': typeof RecruiterJobsJobIdDetailsRoute
  '/jobs/$jobId/interview': typeof RecruiterJobsJobIdInterviewRoute
  '/jobs/$jobId/reports': typeof RecruiterJobsJobIdReportsRoute
  '/jobs/$jobId/': typeof RecruiterJobsJobIdIndexRoute
  '/jobs/$jobId/candidates/$candidateId': typeof RecruiterJobsJobIdCandidatesCandidateIdRoute
  '/jobs/$jobId/candidates/new': typeof RecruiterJobsJobIdCandidatesNewRoute
  '/jobs/$jobId/candidates/': typeof RecruiterJobsJobIdCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RecruiterRouteWithChildren
  '/jobs/new': typeof RecruiterJobsNewRoute
  '/interview/$token/complete': typeof InterviewTokenCompleteRoute
  '/interview/$token/device-check': typeof InterviewTokenDeviceCheckRoute
  '/interview/$token/session': typeof InterviewTokenSessionRoute
  '/jobs': typeof RecruiterJobsIndexRoute
  '/interview/$token': typeof InterviewTokenIndexRoute
  '/jobs/$jobId/details': typeof RecruiterJobsJobIdDetailsRoute
  '/jobs/$jobId/interview': typeof RecruiterJobsJobIdInterviewRoute
  '/jobs/$jobId/reports': typeof RecruiterJobsJobIdReportsRoute
  '/jobs/$jobId': typeof RecruiterJobsJobIdIndexRoute
  '/jobs/$jobId/candidates/$candidateId': typeof RecruiterJobsJobIdCandidatesCandidateIdRoute
  '/jobs/$jobId/candidates/new': typeof RecruiterJobsJobIdCandidatesNewRoute
  '/jobs/$jobId/candidates': typeof RecruiterJobsJobIdCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_recruiter': typeof RecruiterRouteWithChildren
  '/interview/$token': typeof InterviewTokenRouteWithChildren
  '/_recruiter/jobs/$jobId': typeof RecruiterJobsJobIdRouteWithChildren
  '/_recruiter/jobs/new': typeof RecruiterJobsNewRoute
  '/interview/$token/complete': typeof InterviewTokenCompleteRoute
  '/interview/$token/device-check': typeof InterviewTokenDeviceCheckRoute
  '/interview/$token/session': typeof InterviewTokenSessionRoute
  '/_recruiter/jobs/': typeof RecruiterJobsIndexRoute
  '/interview/$token/': typeof InterviewTokenIndexRoute
  '/_recruiter/jobs/$jobId/details': typeof RecruiterJobsJobIdDetailsRoute
  '/_recruiter/jobs/$jobId/interview': typeof RecruiterJobsJobIdInterviewRoute
  '/_recruiter/jobs/$jobId/reports': typeof RecruiterJobsJobIdReportsRoute
  '/_recruiter/jobs/$jobId/': typeof RecruiterJobsJobIdIndexRoute
  '/_recruiter/jobs/$jobId/candidates/$candidateId': typeof RecruiterJobsJobIdCandidatesCandidateIdRoute
  '/_recruiter/jobs/$jobId/candidates/new': typeof RecruiterJobsJobIdCandidatesNewRoute
  '/_recruiter/jobs/$jobId/candidates/': typeof RecruiterJobsJobIdCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interview/$token'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/interview/$token/complete'
    | '/interview/$token/device-check'
    | '/interview/$token/session'
    | '/jobs/'
    | '/interview/$token/'
    | '/jobs/$jobId/details'
    | '/jobs/$jobId/interview'
    | '/jobs/$jobId/reports'
    | '/jobs/$jobId/'
    | '/jobs/$jobId/candidates/$candidateId'
    | '/jobs/$jobId/candidates/new'
    | '/jobs/$jobId/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs/new'
    | '/interview/$token/complete'
    | '/interview/$token/device-check'
    | '/interview/$token/session'
    | '/jobs'
    | '/interview/$token'
    | '/jobs/$jobId/details'
    | '/jobs/$jobId/interview'
    | '/jobs/$jobId/reports'
    | '/jobs/$jobId'
    | '/jobs/$jobId/candidates/$candidateId'
    | '/jobs/$jobId/candidates/new'
    | '/jobs/$jobId/candidates'
  id:
    | '__root__'
    | '/_recruiter'
    | '/interview/$token'
    | '/_recruiter/jobs/$jobId'
    | '/_recruiter/jobs/new'
    | '/interview/$token/complete'
    | '/interview/$token/device-check'
    | '/interview/$token/session'
    | '/_recruiter/jobs/'
    | '/interview/$token/'
    | '/_recruiter/jobs/$jobId/details'
    | '/_recruiter/jobs/$jobId/interview'
    | '/_recruiter/jobs/$jobId/reports'
    | '/_recruiter/jobs/$jobId/'
    | '/_recruiter/jobs/$jobId/candidates/$candidateId'
    | '/_recruiter/jobs/$jobId/candidates/new'
    | '/_recruiter/jobs/$jobId/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RecruiterRoute: typeof RecruiterRouteWithChildren
  InterviewTokenRoute: typeof InterviewTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_recruiter': {
      id: '/_recruiter'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$token': {
      id: '/interview/$token'
      path: '/interview/$token'
      fullPath: '/interview/$token'
      preLoaderRoute: typeof InterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_recruiter/jobs/': {
      id: '/_recruiter/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof RecruiterJobsIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/_recruiter/jobs/$jobId': {
      id: '/_recruiter/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof RecruiterJobsJobIdRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/_recruiter/jobs/new': {
      id: '/_recruiter/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof RecruiterJobsNewRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/interview/$token/': {
      id: '/interview/$token/'
      path: '/'
      fullPath: '/interview/$token/'
      preLoaderRoute: typeof InterviewTokenIndexRouteImport
      parentRoute: typeof InterviewTokenRoute
    }
    '/interview/$token/complete': {
      id: '/interview/$token/complete'
      path: '/complete'
      fullPath: '/interview/$token/complete'
      preLoaderRoute: typeof InterviewTokenCompleteRouteImport
      parentRoute: typeof InterviewTokenRoute
    }
    '/interview/$token/device-check': {
      id: '/interview/$token/device-check'
      path: '/device-check'
      fullPath: '/interview/$token/device-check'
      preLoaderRoute: typeof InterviewTokenDeviceCheckRouteImport
      parentRoute: typeof InterviewTokenRoute
    }
    '/interview/$token/session': {
      id: '/interview/$token/session'
      path: '/session'
      fullPath: '/interview/$token/session'
      preLoaderRoute: typeof InterviewTokenSessionRouteImport
      parentRoute: typeof InterviewTokenRoute
    }
    '/_recruiter/jobs/$jobId/': {
      id: '/_recruiter/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof RecruiterJobsJobIdIndexRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
    '/_recruiter/jobs/$jobId/details': {
      id: '/_recruiter/jobs/$jobId/details'
      path: '/details'
      fullPath: '/jobs/$jobId/details'
      preLoaderRoute: typeof RecruiterJobsJobIdDetailsRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
    '/_recruiter/jobs/$jobId/interview': {
      id: '/_recruiter/jobs/$jobId/interview'
      path: '/interview'
      fullPath: '/jobs/$jobId/interview'
      preLoaderRoute: typeof RecruiterJobsJobIdInterviewRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
    '/_recruiter/jobs/$jobId/reports': {
      id: '/_recruiter/jobs/$jobId/reports'
      path: '/reports'
      fullPath: '/jobs/$jobId/reports'
      preLoaderRoute: typeof RecruiterJobsJobIdReportsRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
    '/_recruiter/jobs/$jobId/candidates/': {
      id: '/_recruiter/jobs/$jobId/candidates/'
      path: '/candidates'
      fullPath: '/jobs/$jobId/candidates/'
      preLoaderRoute: typeof RecruiterJobsJobIdCandidatesIndexRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
    '/_recruiter/jobs/$jobId/candidates/$candidateId': {
      id: '/_recruiter/jobs/$jobId/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/jobs/$jobId/candidates/$candidateId'
      preLoaderRoute: typeof RecruiterJobsJobIdCandidatesCandidateIdRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
    '/_recruiter/jobs/$jobId/candidates/new': {
      id: '/_recruiter/jobs/$jobId/candidates/new'
      path: '/candidates/new'
      fullPath: '/jobs/$jobId/candidates/new'
      preLoaderRoute: typeof RecruiterJobsJobIdCandidatesNewRouteImport
      parentRoute: typeof RecruiterJobsJobIdRoute
    }
  }
}

interface RecruiterJobsJobIdRouteChildren {
  RecruiterJobsJobIdDetailsRoute: typeof RecruiterJobsJobIdDetailsRoute
  RecruiterJobsJobIdInterviewRoute: typeof RecruiterJobsJobIdInterviewRoute
  RecruiterJobsJobIdReportsRoute: typeof RecruiterJobsJobIdReportsRoute
  RecruiterJobsJobIdIndexRoute: typeof RecruiterJobsJobIdIndexRoute
  RecruiterJobsJobIdCandidatesCandidateIdRoute: typeof RecruiterJobsJobIdCandidatesCandidateIdRoute
  RecruiterJobsJobIdCandidatesNewRoute: typeof RecruiterJobsJobIdCandidatesNewRoute
  RecruiterJobsJobIdCandidatesIndexRoute: typeof RecruiterJobsJobIdCandidatesIndexRoute
}

const RecruiterJobsJobIdRouteChildren: RecruiterJobsJobIdRouteChildren = {
  RecruiterJobsJobIdDetailsRoute: RecruiterJobsJobIdDetailsRoute,
  RecruiterJobsJobIdInterviewRoute: RecruiterJobsJobIdInterviewRoute,
  RecruiterJobsJobIdReportsRoute: RecruiterJobsJobIdReportsRoute,
  RecruiterJobsJobIdIndexRoute: RecruiterJobsJobIdIndexRoute,
  RecruiterJobsJobIdCandidatesCandidateIdRoute:
    RecruiterJobsJobIdCandidatesCandidateIdRoute,
  RecruiterJobsJobIdCandidatesNewRoute: RecruiterJobsJobIdCandidatesNewRoute,
  RecruiterJobsJobIdCandidatesIndexRoute:
    RecruiterJobsJobIdCandidatesIndexRoute,
}

const RecruiterJobsJobIdRouteWithChildren =
  RecruiterJobsJobIdRoute._addFileChildren(RecruiterJobsJobIdRouteChildren)

interface RecruiterRouteChildren {
  RecruiterJobsJobIdRoute: typeof RecruiterJobsJobIdRouteWithChildren
  RecruiterJobsNewRoute: typeof RecruiterJobsNewRoute
  RecruiterJobsIndexRoute: typeof RecruiterJobsIndexRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterJobsJobIdRoute: RecruiterJobsJobIdRouteWithChildren,
  RecruiterJobsNewRoute: RecruiterJobsNewRoute,
  RecruiterJobsIndexRoute: RecruiterJobsIndexRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

interface InterviewTokenRouteChildren {
  InterviewTokenCompleteRoute: typeof InterviewTokenCompleteRoute
  InterviewTokenDeviceCheckRoute: typeof InterviewTokenDeviceCheckRoute
  InterviewTokenSessionRoute: typeof InterviewTokenSessionRoute
  InterviewTokenIndexRoute: typeof InterviewTokenIndexRoute
}

const InterviewTokenRouteChildren: InterviewTokenRouteChildren = {
  InterviewTokenCompleteRoute: InterviewTokenCompleteRoute,
  InterviewTokenDeviceCheckRoute: InterviewTokenDeviceCheckRoute,
  InterviewTokenSessionRoute: InterviewTokenSessionRoute,
  InterviewTokenIndexRoute: InterviewTokenIndexRoute,
}

const InterviewTokenRouteWithChildren = InterviewTokenRoute._addFileChildren(
  InterviewTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RecruiterRoute: RecruiterRouteWithChildren,
  InterviewTokenRoute: InterviewTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
